import {SocialNetwork} from "../classes/social-network/social-network";
import {SocialNetworkType} from "../enums/social-network-type";

export let socialNetworks: SocialNetwork[] = [
  new SocialNetwork(
    'Email',
    null,
    '/about-us',
    'contact-email',
    SocialNetworkType.preferred,
    '/assets/external-icons/envelope.svg',
    '/assets/other/email.png',
  ), new SocialNetwork(
    'Facebook',
    'https://www.facebook.com/Shirokuro.club',
    'contact-facebook',
    null,
    SocialNetworkType.preferred,
    '/assets/external-icons/facebook.svg',
    null,
  ), new SocialNetwork(
    'Twitter',
    'https://twitter.com/shirokuro_club',
    null,
    'contact-twitter',
    SocialNetworkType.preferred,
    '/assets/external-icons/twitter.svg',
    null,
  ), new SocialNetwork(
    'Instagram',
    'https://www.instagram.com/shirokuro_club/',
    null,
    'contact-instagram',
    SocialNetworkType.preferred,
    '/assets/external-icons/instagram.svg',
    null,
  ), new SocialNetwork(
    'Messenger',
    'https://m.me/shirokuro.club',
    null,
    'contact-fragment',
    SocialNetworkType.preferred,
    '/assets/external-icons/messenger.svg',
    null,
  ), new SocialNetwork(
    'BattleFy',
    'https://battlefy.com/shirokuroclub',
    null,
    'contact-battlefy',
    SocialNetworkType.activities,
    '/assets/external-icons/battlefy.png',
    null,
  ), new SocialNetwork(
    'Eventbrite',
    'https://www.eventbrite.es/o/shirokuroclub-52632586033',
    null,
    null,
    SocialNetworkType.activities,
    '/assets/external-icons/eventbrite.svg',
    null,
  ), new SocialNetwork(
    'Github',
    'https://gitlab.com/shirokuro.club',
    null,
    null,
    SocialNetworkType.restricted,
    '/assets/external-icons/gitlab.svg',
    null,
  ), new SocialNetwork(
    'Trello',
    'https://trello.com/w/shirokuroclub/',
    null,
    'contact-trello',
    SocialNetworkType.restricted,
    '/assets/external-icons/trello.svg',
    null,
  ), new SocialNetwork(
    'Matrix',
    'https://matrix.shirokuro.club/',
    null,
    'contact-matrix',
    SocialNetworkType.restricted,
    '/assets/external-icons/matrix.svg',
    null,
  ), new SocialNetwork(
    'Discord',
    null,
    null,
    'contact-discord',
    SocialNetworkType.restricted,
    '/assets/external-icons/discord.svg',
    null,
  ), new SocialNetwork(
    'WhatsApp',
    null,
    null,
    'contact-whatsapp',
    SocialNetworkType.restricted,
    '/assets/external-icons/whatsapp.svg',
    null,
  ),
]
